{
	"openapi": "3.0.0",
	"info": {
		"title": "Flight API",
		"description": "Flight APIs to manage deployments, flight plans and flight sessions",
		"version": "0.0.1-DRAFT"
	},
	"servers": [
		{
			"url": "https://localhost:8080/",
			"description": "Development Server"
		}
	],
	"paths": {
		"/flight/deployments": {
			"$ref": "#/components/routes/deployments"
		},
		"/flight/deployments/{deployment_id}": {
			"$ref": "#/components/routes/deployments-{deployment_id}"
		},
		"/flight/deployments/{deployment_id}/plans": {
			"$ref": "#/components/routes/deployments-{deployment_id}-plans"
		},
		"/flight/deployments/{deployment_id}/plans/{flight_plan_id}": {
			"$ref": "#/components/routes/deployments-{deployment_id}-plans-{flight_plan_id}"
		},
		"/flight/deployments/{deployment_id}/sessions": {
			"$ref": "#/components/routes/deployments-{deployment_id}-sessions"
		},
		"/flight/deployments/{deployment_id}/sessions/{flight_session_id}": {
			"$ref": "#/components/routes/deployments-{deployment_id}-sessions-{flight_session_id}"
		}
	},
	"tags": [
		{
			"name": "Deployments",
			"description": "<p>Every time pilots are activated to fly drones, it is known as a <code>deployment</code>. A <code>deployment</code> is part of larger <code>project</code>, typically spans at least 1 flight session (or maybe a few minutes to a few hours), or multiple flight sessions. For each <code>deployment</code>, a leader, known as the <code>deployment lead</code> will plan the deployment for success, enlisting <code>pilots</code>, <code>drones</code>, and other equipment necessary. Proper <code>risk management</code> is required for every deployment, as are <code>permits</code> by the relevant authority (such as an Activity Permit by CAAS). Insurance coverage might also be purchased on a <code>deployment</code> basis instead of annual basis.</p> <p>To start working with deployments, we first have to create a deployment. Call the <code>/flights/deployments</code> endpoint with the <code>POST</code> method to create a new deployment. At minimum, you should pass in the following details in the request body:</p> <table> <thead> <tr> <th>Item</th> <th>Type</th> <th>Description</th> </tr> </thead> <tbody> <tr> <td><code>name</code></td> <td>String</td> <td>Name of the deployment</td> </tr> <tr> <td><code>drones</code></td> <td>Array</td> <td>Array of drone IDs to be used for the deployment</td> </tr> <tr> <td><code>deployment_lead_id</code></td> <td>String</td> <td>User ID of the deployment lead</td> </tr> <tr> <td><code>start_date</code></td> <td>String</td> <td>Start date of deployment in epoch (Unix timestamp), converted to milliseconds (ms)</td> </tr> <tr> <td><code>end_date</code></td> <td>String</td> <td>End date of deployment in epoch (Unix timestamp), converted to milliseconds (ms)</td> </tr> <tr> <td><code>deployment_area</code></td> <td>String</td> <td>GeoJSON string representation of the deployment area</td> </tr> </tbody> </table> <p>There are some additional details that you can add to the request body to flesh out your deployment details even further:</p> <table> <thead> <tr> <th>Item</th> <th>Type</th> <th>Description</th> </tr> </thead> <tbody> <tr> <td><code>batteries</code></td> <td>Array</td> <td>Array of battery IDs to be used for the deployment</td> </tr> <tr> <td><code>cameras</code></td> <td>Array</td> <td>Array of camera IDs to be used for the deployment</td> </tr> <tr> <td><code>personnel</code></td> <td>Array</td> <td>Array of user IDs of the personnel involved in the deployment</td> </tr> <tr> <td><code>purpose</code></td> <td>String</td> <td>Description of the purpose of deployment</td> </tr> </tbody> </table> <p>A deployment that has been successfully created will return a response with a <code>\"success\": true</code> body and a <code>200 OK</code> status. For more detailed response format, refer to the endpoint <code>POST /flight/deployments</code>.</p><p>Once you have successfully created your deployment, you are ready to draw up a flight plan.</p>"
		},
		{
			"name": "Flight Plans",
			"description": "<p>Every flight requires a valid and approved <code>flight plan</code> before your drone can safely take off. There are many factors that need to be taken into account when creating a <code>flight plan</code>, including the <code>plan type</code>, <code>requirements</code>, <code>commands</code>, and more. Every <code>flight plan</code> must be tagged to an existing <code>deployment</code>, and each <code>flight plan</code> can be reused as required for multiple <code>flight sessions</code>. </p> <p>To start, you can create a new flight plan by calling the <code>/flight/deployments/{deployment_id}/plans</code> endpoint with the <code>POST</code> method. Note that the <code>deployment_id</code> parameter in the request URL has to be a valid <code>deployment_id</code> belonging to your company. </p> <p>You should pass in at minimum the following details in the request body:</p> <table> <thead> <tr> <th>Item</th> <th>Type</th> <th>Description</th> </tr> </thead> <tbody> <tr> <td><code>plan_type</code></td> <td>String</td> <td>The type of the flight plan</td> </tr> <tr> <td><code>description</code></td> <td>String</td> <td>Description of the flight plan</td> </tr> <tr> <td><code>plan</code></td> <td>Object</td> <td>Object representing the actual flight plan</td> </tr> </tbody> </table> <p>The <code>plan</code> object has the following properties:</p> <table> <thead> <tr> <th>Property</th> <th>Type</th> <th>Description</th> </tr> </thead> <tbody> <tr> <td><code>requirements</code></td> <td>Object</td> <td>Requirements of the flight plan</td> </tr> <tr> <td><code>commands</code></td> <td>Array of Objects</td> <td>Array of command objects that describe the commands to be executed during the flight</td> </tr> </tbody> </table> <p>A flight plan that is successfully created will return a response with a <code>\"success\": true</code> body and a <code>200 OK</code> status. For more detailed response format, refer to the endpoint <code>POST /flight/deployments/{deployment_id}/plans</code>.</p><p>Once your flight plan has been created and approved, you are ready to begin your first flight session!</p>"
		},
		{
			"name": "Flight Sessions",
			"description": "<p>Once you have your flight plan approved, you are ready to fly!</p> <p>Each drone flight is represented by a flight session. Each <strong><code>flight session</code></strong> must be tagged to a valid and approved <strong><code>flight plan</code></strong> and an existing <strong><code>deployment</code></strong>. This set of endpoints allow you to manage and log the flight history of your deployments easily.</p> <p>To create a new <code>flight session</code>, use the <code>/flight/deployments/{deployment_id}/sessions</code> endpoint with the <code>POST</code> method. Note that the <code>deployment_id</code> parameter in the request URL has to be a valid <code>deployment_id</code> belonging to your company.</p> <p>You should pass in at minimum the following details in the request body:</p> <table> <thead> <tr> <th>Item</th> <th>Type</th> <th>Description</th> </tr> </thead> <tbody> <tr> <td><code>flight_plan_id</code></td> <td>String</td> <td>A valid and approved flight plan ID</td> </tr> <tr> <td><code>start_date_time</code></td> <td>String</td> <td>Start time of flight session in epoch (Unix timestamp), converted to milliseconds (ms)</td> </tr> <tr> <td><code>end_date_time</code></td> <td>String</td> <td>End time of flight session in epoch (Unix timestamp), converted to milliseconds (ms)</td> </tr> </tbody> </table> <p>A flight session that is successfully logged to your deployment will return the following response:</p> <pre><code>{ <br>  \"success\": true, <br>  \"data\": {<br>    \"flight_session_id\": \"FLIGHT_SESSION_ID\", <br>    \"flight_plan_id\": \"FLIGHT_PLAN_ID\", <br>    \"deployment_id\": \"DEPLOYMENT_ID\", <br>    \"start_date_time\": START_TIME, <br>    \"end_date_time\": END_TIME <br>  } <br>} </code></pre>"
		}
	],
	"components": {
		"routes": {
			"deployments": {
				"get": {
					"tags": [
						"Deployments"
					],
					"summary": "Get all deployments",
					"description": "Get all deployments belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/options"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"type": "array",
												"description": "Array of deployments",
												"items": {
													"$ref": "#/components/schemas/deployment_data"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"post": {
					"tags": [
						"Deployments"
					],
					"summary": "Create new deployment",
					"description": "Create a new deployment belonging to the company of the user.",
					"requestBody": {
						"description": "**Required values:** `name`, `drones`, `lead`, `start_date`, `end_date`, `geo_json`<br><br> **Optional values:** `batteries`, `cameras`, `personnel`, `purpose`",
						"required": true,
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/deployment"
								}
							}
						}
					},
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/deployment_data"
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"deployments-{deployment_id}": {
				"get": {
					"tags": [
						"Deployments"
					],
					"summary": "Get a deployment",
					"description": "Get a specific deployment belonging to the company of the user",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"type": "array",
												"description": "Array of deployments",
												"items": {
													"$ref": "#/components/schemas/deployment_data"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"patch": {
					"tags": [
						"Deployments"
					],
					"summary": "Update a deployment",
					"description": "Update a specific deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						}
					],
					"requestBody": {
						"description": " **Optional values:** `name`, `drones`, `lead`, `batteries`, `cameras`, `personnel`, `purpose`, `start_date`, `end_date`, `geo_json`",
						"required": true,
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/deployment"
								}
							}
						}
					},
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/deployment_data"
											}
										}
									}
								}
							}
						}
					}
				},
				"delete": {
					"tags": [
						"Deployments"
					],
					"summary": "Delete a deployment",
					"description": "Delete a specific deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/deployment_data"
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"deployments-{deployment_id}-plans": {
				"get": {
					"tags": [
						"Flight Plans"
					],
					"summary": "Get all deployment flight plans",
					"description": "Get all flight plans of a specific deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"type": "array",
												"description": "Array of flight plans",
												"items": {
													"$ref": "#/components/schemas/flight_plan_data"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"post": {
					"tags": [
						"Flight Plans"
					],
					"summary": "Create new flight plan",
					"description": "Create a new flight plan for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						}
					],
					"requestBody": {
						"description": "**Required values:** `plan_type`, `description`, `plan`",
						"required": true,
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/flight_plan"
								}
							}
						}
					},
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_plan_data"
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"deployments-{deployment_id}-plans-{flight_plan_id}": {
				"get": {
					"tags": [
						"Flight Plans"
					],
					"summary": "Get a flight plan",
					"description": "Get a specific flight plan for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						},
						{
							"$ref": "#/components/parameters/flight_plan_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_plan_data"
											}
										}
									}
								}
							}
						}
					}
				},
				"patch": {
					"tags": [
						"Flight Plans"
					],
					"summary": "Update a flight plan",
					"description": "Update a specific flight plan for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						},
						{
							"$ref": "#/components/parameters/flight_plan_id"
						}
					],
					"requestBody": {
						"description": "**Optional values:** `plan_type`, `description`, `plan`",
						"required": true,
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/flight_plan"
								}
							}
						}
					},
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_plan_data"
											}
										}
									}
								}
							}
						}
					}
				},
				"delete": {
					"tags": [
						"Flight Plans"
					],
					"summary": "Delete a flight plan",
					"description": "Delete a specific flight plan for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						},
						{
							"$ref": "#/components/parameters/flight_plan_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_plan_data"
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"deployments-{deployment_id}-sessions": {
				"get": {
					"tags": [
						"Flight Sessions"
					],
					"summary": "Get all deployment flight sessions",
					"description": "Get all flight sessions of a specific deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"type": "array",
												"description": "Array of flight sessions",
												"items": {
													"$ref": "#/components/schemas/flight_session_data"
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"post": {
					"tags": [
						"Flight Sessions"
					],
					"summary": "Create new flight session",
					"description": "Create a new flight session for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						}
					],
					"requestBody": {
						"description": "**Required values:** `flight_plan_id`, `start_date_time`, `end_date_time`",
						"required": true,
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/flight_session"
								}
							}
						}
					},
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_session_data"
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"deployments-{deployment_id}-sessions-{flight_session_id}": {
				"get": {
					"tags": [
						"Flight Sessions"
					],
					"summary": "Get a flight session",
					"description": "Get a specific flight session for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						},
						{
							"$ref": "#/components/parameters/flight_session_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_session_data"
											}
										}
									}
								}
							}
						}
					}
				},
				"patch": {
					"tags": [
						"Flight Sessions"
					],
					"summary": "Update a flight session",
					"description": "Update a specific flight session for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						},
						{
							"$ref": "#/components/parameters/flight_session_id"
						}
					],
					"requestBody": {
						"description": "**Optional values:** `flight_plan_id`, `start_date_time`, `end_date_time`",
						"required": true,
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/flight_session"
								}
							}
						}
					},
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_session_data"
											}
										}
									}
								}
							}
						}
					}
				},
				"delete": {
					"tags": [
						"Flight Sessions"
					],
					"summary": "Delete a flight session",
					"description": "Delete a specific flight session for a deployment belonging to the company of the user.",
					"parameters": [
						{
							"$ref": "#/components/parameters/deployment_id"
						},
						{
							"$ref": "#/components/parameters/flight_session_id"
						}
					],
					"responses": {
						"200": {
							"description": "A successful request",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"success": {
												"type": "boolean",
												"example": true,
												"description": "Status of the response"
											},
											"data": {
												"$ref": "#/components/schemas/flight_session_data"
											}
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"parameters": {
			"options": {
				"name": "options",
				"in": "query",
				"required": false,
				"description": "Deep/shallow fetch option (Default: Shallow)",
				"schema": {
					"type": "string",
					"enum": [
						"deep",
						"shallow"
					]
				}
			},
			"deployment_id": {
				"name": "deployment_id",
				"in": "path",
				"required": true,
				"description": "Deployment ID",
				"schema": {
					"type": "string"
				}
			},
			"flight_plan_id": {
				"name": "flight_plan_id",
				"in": "path",
				"required": true,
				"description": "Flight Plan ID",
				"schema": {
					"type": "string"
				}
			},
			"flight_session_id": {
				"name": "flight_session_id",
				"in": "path",
				"required": true,
				"description": "Flight Session ID",
				"schema": {
					"type": "string"
				}
			},
			"company_id": {
				"name": "company_id",
				"in": "path",
				"required": true,
				"description": "Company ID",
				"schema": {
					"type": "string"
				}
			}
		},
		"schemas": {
			"deployment": {
				"type": "object",
				"required": [
					"name"
				],
				"properties": {
					"name": {
						"type": "string",
						"example": "Zhao Shi Chong's Deployment on 2018-05-22",
						"description": "Name of deployment"
					},
					"drones": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "Drone ID"
						},
						"example": [
							"0c5c21b6a42fadb018a5d1863c312345",
							"0c5c21b6a42fadb018a5d1863c312345"
						]
					},
					"batteries": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "Battery ID"
						},
						"example": [
							"0c5c21b6a42fadb018a5d1863c312345",
							"0c5c21b6a42fadb018a5d1863c312345"
						]
					},
					"cameras": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "Camera ID"
						},
						"example": [
							"0c5c21b6a42fadb018a5d1863c312345",
							"0c5c21b6a42fadb018a5d1863c312345"
						]
					},
					"personnel": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "User ID"
						},
						"example": [
							"0c5c21b6a42fadb018a5d1863c312345",
							"0c5c21b6a42fadb018a5d1863c312345"
						]
					},
					"lead": {
						"type": "string",
						"example": "0c5c21b6a42fadb018a5d1863c312345"
					},
					"purpose": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "Description of purpose"
						},
						"example": [
							"Photography",
							"Analytics",
							"Security checks"
						]
					},
					"start_date": {
						"type": "string",
						"example": "1559571926000",
						"description": "Start date in milliseconds"
					},
					"end_date": {
						"type": "string",
						"example": "1559572026000",
						"description": "End date in milliseconds"
					},
					"geo_json": {
						"type": "string",
						"example": "{ \"type\": \"Polygon\", \"coordinates\": [ [ [ -118.37099075317383, 33.85505651142062 ], [ -118.37305068969727, 33.85502978214579 ], [ -118.37347984313963, 33.854673391015496 ], [ -118.37306141853333, 33.85231226221667 ], [ -118.37193489074707, 33.85174201755203 ], [ -118.36997151374815, 33.85176874785573 ], [ -118.36995005607605, 33.8528112231754 ], [ -118.37099075317383, 33.85505651142062 ] ] ] }",
						"description": "GeoJSON Polygon of deployment area"
					}
				}
			},
			"deployment_data": {
				"type": "object",
				"required": [
					"name"
				],
				"properties": {
					"name": {
						"type": "string",
						"example": "Zhao Shi Chong's Deployment on 2018-05-22",
						"description": "Name of deployment"
					},
					"deployment_id": {
						"type": "string",
						"example": "0c5c21b6a42fadb018a5d1863c312345",
						"description": "Deployment ID"
					},
					"drones": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								},
								"drone_id": {
									"type": "string"
								},
								"model_name": {
									"type": "string"
								},
								"model_id": {
									"type": "string"
								}
							}
						},
						"example": [
							{
								"name": "DEV-001",
								"drone_id": "0c5c21b6a42fadb018a5d1863c312345",
								"model_name": "M400 UAV",
								"model_id": "0c5c21b6a42fadb018a5d1863c312345"
							},
							{
								"name": "DEV-002",
								"drone_id": "0c5c21b6a42fadb018a5d1863c312345",
								"model_name": "M408 UAV",
								"model_id": "0c5c21b6a42fadb018a5d1863c312345"
							}
						]
					},
					"batteries": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								},
								"battery_id": {
									"type": "string"
								},
								"model_name": {
									"type": "string"
								},
								"model_id": {
									"type": "string"
								}
							}
						},
						"example": [
							{
								"name": "BATTERY-001",
								"battery_id": "0c5c21b6a42fadb018a5d1863c312345",
								"model_name": "Multistar 6S 6600",
								"model_id": "0c5c21b6a42fadb018a5d1863c312345"
							},
							{
								"name": "BATTERY-002",
								"battery_id": "0c5c21b6a42fadb018a5d1863c312345",
								"model_name": "Multistar 6S 8000",
								"model_id": "0c5c21b6a42fadb018a5d1863c312345"
							}
						]
					},
					"cameras": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								},
								"camera_id": {
									"type": "string"
								},
								"model_name": {
									"type": "string"
								},
								"model_id": {
									"type": "string"
								}
							}
						},
						"example": [
							{
								"name": "CAMERA-001",
								"camera_id": "0c5c21b6a42fadb018a5d1863c312345",
								"model_name": "Huawei P30 Pro",
								"model_id": "0c5c21b6a42fadb018a5d1863c312345"
							},
							{
								"name": "CAMERA-002",
								"camera_id": "0c5c21b6a42fadb018a5d1863c312345",
								"model_name": "Huawei P30 Pro X50",
								"model_id": "0c5c21b6a42fadb018a5d1863c312345"
							}
						]
					},
					"personnel": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								},
								"user_id": {
									"type": "string"
								}
							}
						},
						"example": [
							{
								"name": "Jayson Beltran",
								"user_id": "0c5c21b6a42fadb018a5d1863c312345"
							},
							{
								"name": "Ahmed Major",
								"user_id": "0c5c21b6a42fadb018a5d1863c312345"
							}
						]
					},
					"lead": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"user_id": {
								"type": "string"
							}
						},
						"example": {
							"name": "Asher Solomon",
							"user_id": "0c5c21b6a42fadb018a5d1863c312345"
						}
					},
					"purpose": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "Description of purpose"
						},
						"example": [
							"Photography",
							"Analytics",
							"Security checks"
						]
					},
					"start_date": {
						"type": "string",
						"example": "1559571926000",
						"description": "Start date in milliseconds"
					},
					"end_date": {
						"type": "string",
						"example": "1559572026000",
						"description": "End date in milliseconds"
					},
					"geo_json": {
						"type": "string",
						"example": "{ \"type\": \"Polygon\", \"coordinates\": [ [ [ -118.37099075317383, 33.85505651142062 ], [ -118.37305068969727, 33.85502978214579 ], [ -118.37347984313963, 33.854673391015496 ], [ -118.37306141853333, 33.85231226221667 ], [ -118.37193489074707, 33.85174201755203 ], [ -118.36997151374815, 33.85176874785573 ], [ -118.36995005607605, 33.8528112231754 ], [ -118.37099075317383, 33.85505651142062 ] ] ] }",
						"description": "GeoJSON Polygon of deployment area"
					}
				}
			},
			"flight_plan": {
				"type": "object",
				"properties": {
					"plan_type": {
						"type": "string",
						"example": "ardupilot",
						"description": "Type of plan"
					},
					"description": {
						"type": "string",
						"example": "Best flight plan ever",
						"description": "Description of flight plan"
					},
					"plan": {
						"type": "object",
						"properties": {
							"requirements": {
								"type": "object"
							},
							"commands": {
								"type": "array",
								"items": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string",
											"example": "22",
											"description": "Command ID"
										},
										"param1": {
											"type": "string",
											"example": "15",
											"description": "Command parameter 1"
										},
										"param2": {
											"type": "string",
											"example": "16",
											"description": "Command parameter 2"
										},
										"param3": {
											"type": "string",
											"example": "17",
											"description": "Command parameter 3"
										},
										"param4": {
											"type": "string",
											"example": "18",
											"description": "Command parameter 4"
										},
										"param5": {
											"type": "string",
											"example": "19",
											"description": "Command parameter 5"
										},
										"param6": {
											"type": "string",
											"example": "20",
											"description": "Command parameter 6"
										},
										"param7": {
											"type": "string",
											"example": "21",
											"description": "Command parameter 7"
										},
										"description": {
											"type": "string",
											"example": "Take off (location TBD)",
											"description": "Description of command"
										}
									}
								}
							}
						}
					}
				}
			},
			"flight_plan_data": {
				"type": "object",
				"properties": {
					"flight_plan_id": {
						"type": "string",
						"example": "0c5c21b6a42fadb018a5d1863c312345",
						"description": "Flight Plan ID"
					},
					"deployment_id": {
						"type": "string",
						"example": "0c5c21b6a42fadb018a5d1863c312345",
						"description": "Deployment ID"
					},
					"plan_type": {
						"type": "string",
						"example": "ardupilot",
						"description": "Type of plan"
					},
					"description": {
						"type": "string",
						"example": "Best flight plan ever",
						"description": "Description of flight plan"
					},
					"last_modified_date": {
						"type": "string",
						"description": "Datetime in milliseconds of the last modification"
					},
					"last_modified_by": {
						"type": "string",
						"description": "User ID of the last user that modified this flight plan"
					},
					"plan": {
						"type": "object",
						"properties": {
							"requirements": {
								"type": "object"
							},
							"commands": {
								"type": "array",
								"items": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string",
											"example": "22",
											"description": "Command ID"
										},
										"param1": {
											"type": "string",
											"example": "15",
											"description": "Command parameter 1 (Camera)"
										},
										"param2": {
											"type": "string",
											"example": "16",
											"description": "Command parameter 2 (Target)"
										},
										"param3": {
											"type": "string",
											"example": "17",
											"description": "Command parameter 3 (Return Location)"
										},
										"param4": {
											"type": "string",
											"example": "18",
											"description": "Command parameter 4 (Navigate)"
										},
										"param5": {
											"type": "string",
											"example": "19",
											"description": "Command parameter 5 (Move)"
										},
										"param6": {
											"type": "string",
											"example": "20",
											"description": "Command parameter 6 (Yaw)"
										},
										"param7": {
											"type": "string",
											"example": "21",
											"description": "Command parameter 7 (Take Off)"
										},
										"description": {
											"type": "string",
											"example": "Take off (location TBD)",
											"description": "Description of command"
										}
									}
								}
							}
						}
					}
				}
			},
			"flight_session": {
				"type": "object",
				"properties": {
					"flight_plan_id": {
						"type": "string",
						"example": "034611ca922f665baa9444059fad251c",
						"description": "Flight plan ID of the flight session"
					},
					"start_date_time": {
						"type": "number",
						"example": 1527469200000,
						"description": "Timestamp of start date in milliseconds"
					},
					"end_date_time": {
						"type": "number",
						"example": 1527479200000,
						"description": "Timestamp of end date in milliseconds"
					}
				}
			},
			"flight_session_data": {
				"type": "object",
				"properties": {
					"flight_session_id": {
						"type": "string",
						"example": "034611ca922f665baa9444059fad251c",
						"description": "Flight session ID"
					},
					"flight_plan_id": {
						"type": "string",
						"example": "034611ca922f665baa9444059fad251c",
						"description": "Flight plan ID of the flight session"
					},
					"deployment_id": {
						"type": "string",
						"example": "034611ca922f665baa9444059fad251c",
						"description": "Deployment ID of the flight session"
					},
					"start_date_time": {
						"type": "number",
						"example": 1527469200000,
						"description": "Timestamp of start date in milliseconds"
					},
					"end_date_time": {
						"type": "number",
						"example": 1527479200000,
						"description": "Timestamp of end date in milliseconds"
					}
				}
			}
		}
	}
}